#ifndef PROGETTO_PROGRAMMAZIONE_GAMESTATE_HPP
#define PROGETTO_PROGRAMMAZIONE_GAMESTATE_HPP

enum GameState{
    PAUSE,
    IN_GAME,
    LOSS,
    RESTART,
    QUIT
};

#endif //PROGETTO_PROGRAMMAZIONE_GAMESTATE_HPP
